### ISSUE TITLE
Metadata rating needs to always return a float 

### ISSUE THREAD

**Issue by zopsi** [DeeZem/Superchillin.bundle#2]
In ServiceCode.pys line 34 needs to be changed to return a float instead of an int in order to prevent Plex from displaying "This Channel is not responding" to the user

Original:   `rating =           float(rating[0]) if rating else 0`
Changed: `rating =           float(rating[0]) if rating else float(0)`

**Comment by DeeZem** [comment]
Thanks for letting me know about this issue. It's fixed now. When I have some free time I'll have to update the IMDB lookup code to handle their new html.
