### ISSUE TITLE
Channel not working on web and Mobile Android app.

### ISSUE THREAD

**Issue by Pharrcyde** [DeeZem/Superchillin.bundle#4]
One of the recent Plex updates has caused the channel from working for me. Now I get "this channel is not responding" in plex web and on the mobile app I get http://i.imgur.com/I45zbFF.jpg

Weirdly it seems to working fine on the Roku app.

Is it just me?

**Comment by Pharrcyde** [comment]
To stop working*

**Comment by DeeZem** [comment]
Looks like this is an issue with loaded metadata from IMDB. I've removed the directors and writers metadata for now and that seems to have fixed the issue.

**Comment by Pharrcyde** [comment]
Thanks! I really appreciate it man!
