### ISSUE TITLE
This channel is not responding when loading Movies

### ISSUE THREAD

**Issue by cliffmu-zz** [DeeZem/Superchillin.bundle#7]
First off, thanks so much for your work on this channel!

When I view movies, the channel only properly loads "Order by A-Z" and "High Bitrate Test". I'm assuming this is because "Order by Latest", "Order by Release Date" and "Order by IMDb Rating" are returning too many results (8,000+). 

Am I the only one experiencing this behavior? Is there a way to minimize the strain to load all items?

**Comment by DeeZem** [comment]
You're right, as the database gets bigger these pages take longer to load and some clients might timeout before the processing can finish.

I'll work on adding pagination to fix this. It might take a little while to implement, but it should fix the problem.

**Comment by cliffmu-zz** [comment]
I can confirm that this behavior occurs on my OSX laptop using Chrome and Apple TV 4. Perhaps your fix for "Fails to retrieve content... Sometime" that allows the video to load without images and IMDb can help reduce strain. I'll check later.

**Comment by Pharrcyde** [comment]
I can also confirm the same thing happens to me when using the Plex on my Chromebook flip.
Fortunately for me my Chromebook supports the Playstore in the beta channel so I can just use the Android Plex app just fine. It also works fine on my Note 7. It does show a blank page for a few seconds but eventually loads everything on the Android app.

Quick question (off topic): When watching superchillin using Plex I noticed it shows my Dedicated servers ip at http://superchillin.com/access.php.   Does that mean the ip limit doesn't affect Plex as everyone would be using superchillin from the same ip?

**Comment by DeeZem** [comment]
@DarkIllusi0n regarding your off topic question:
You are correct. Plex channels run on the server, not the client. So any requests the channel has to make run from the Plex server's internet connection.

I guess technically that means you could use Plex as a sort of proxy to stream superchillin content to more IP addresses than you're supposed to, but it's unlikely the average user has enough network speed and processing power to do that on a large scale.

**Comment by DeeZem** [comment]
I just committed a change that should help with this issue. Everything now paginates, so it will only load say 50 records and then have a "Next Page" button.

The number of records displayed per page can be customized in the channel settings. Default is 200.

Let me know if this fixes your problem.

**Comment by Pharrcyde** [comment]
"Order by Latest", "Order by Release Date" and "Order by IMDb Rating" now load on the web browser, just can't scroll too fast, lol.

Thanks!
