### ISSUE TITLE
Server list

### ISSUE THREAD

**Issue by cliffmu-zz** [DeeZem/Superchillin.bundle#8]
Some servers listed in setting have been deleted. This caused issues for me because I was still pointing to a server that no longer exists and therefore the channel wasn't working (took me a little while to figure out). Consider updating list for others to avoid confusion or have the list auto populate somehow automatically in case of future changes.

**Comment by Pharrcyde** [comment]
Didn't he already do this a few weeks ago?

https://github.com/DeeZem/Superchillin.bundle/commit/b22a1136814e774bdab4c6ccc8edaae1dc8a4592

http://i.imgur.com/pTsAM1h.png

**Comment by DeeZem** [comment]
This issue had already been fixed in b22a113. There was some left over bloat in __init__.py that cliffmu cleaned up with 35eaa47.
